version: '2.2'

services:

    database:
        image: postgres:12.3-alpine
        restart: always
        env_file: backend/.env
        ports:
            - 5432:5432
        volumes:
          - /home/volumes/postgres:/var/lib/postgresql/data
        
    # backend:
    #     build: backend/.
    #     restart: always
    #     env_file: backend/.env
    #     depends_on:
    #         - database  
    #     ports:
    #         - 8000:8000
    #     volumes:
    #       - /home/volumes/backend/static:/backend/staticfiles
    #       - /home/volumes/backend/media:/backend/media
          
    #     command: ./main.sh

    broker:
        build: broker/.
        restart: always
        ports: 
            - 1883:1883
            - 9001:9001